# Generated by Django 4.1.7 on 2023-02-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('bio', models.CharField(max_length=1000)),
                ('age', models.PositiveBigIntegerField()),
            ],
        ),
    ]
