# Generated by Django 4.1.6 on 2023-02-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=50)),
                ('patent_no', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=10)),
            ],
        ),
    ]
