# Generated by Django 4.1.6 on 2023-02-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_companydatatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorsDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peoples_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('patent_no', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatentDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatentNumber', models.CharField(max_length=20)),
                ('applicant', models.CharField(max_length=500)),
                ('Country', models.CharField(max_length=5)),
                ('FilingDate', models.CharField(max_length=10)),
                ('GrantDate', models.CharField(max_length=10)),
                ('Patentlang', models.CharField(max_length=10)),
                ('PatentTitle', models.CharField(max_length=1000)),
                ('PatentxmlLink', models.CharField(max_length=1000)),
                ('Cpc_Class', models.CharField(max_length=1000)),
                ('kind', models.CharField(max_length=10)),
                ('application_date', models.CharField(max_length=10)),
                ('inventors_name', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
