# Generated by Django 4.1.6 on 2023-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_inventorsdatatable_patentdatatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorsdatatable',
            name='city',
            field=models.CharField(max_length=200),
        ),
    ]
