# Generated by Django 4.1.6 on 2023-02-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_rename_country_patentdatatable_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentdatatable',
            name='company_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='patentdatatable',
            name='cpc_class',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='patentdatatable',
            name='inventors_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='patentdatatable',
            name='patenttitle',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='patentdatatable',
            name='patentxmllink',
            field=models.CharField(max_length=2000),
        ),
    ]
