# Generated by Django 4.1.6 on 2023-02-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_patentdatatable_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentdatatable',
            name='company_name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='patentdatatable',
            name='inventors_name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='patentdatatable',
            name='patenttitle',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='patentdatatable',
            name='patentxmllink',
            field=models.CharField(max_length=5000),
        ),
    ]
